name: app

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - '.github/workflows/app.yml'
  pull_request:
    paths:
      - 'app/**'
      - '.github/workflows/app.yml'

defaults:
  run:
    working-directory: app

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test
